# Generated by Django 4.2.9 on 2024-01-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_account_type_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
