# Generated by Django 4.2.9 on 2024-02-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
