# Generated by Django 4.2.9 on 2024-02-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_limit',
            field=models.BooleanField(default=True),
        ),
    ]
