# Generated by Django 4.2.9 on 2024-07-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='internal_revenew_required',
            field=models.BooleanField(default=False),
        ),
    ]
