# Generated by Django 4.2.9 on 2024-02-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_bank_name_transaction_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='routing_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
